<a href="https://colab.research.google.com/github/ankita1200/Machine-Learning-Topics/blob/main/TensorflowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

Basic Initailization steps

In [2]:
# shape 1 by 1 - scalar
x = tf.constant(1, shape=(1,1), dtype=tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

In [3]:
# 2 dimensional rows=2 , col=3
x = tf.constant([[1,2,3],[4,5,6]], shape=(2,3), dtype=tf.float32)
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
# 2 dimensional rows=2 , col=3
x = tf.constant([[1,2,3],[4,5,6]], shape=(6,1), dtype=tf.float32)
x

<tf.Tensor: shape=(6, 1), dtype=float32, numpy=
array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]], dtype=float32)>

In [5]:
tf.zeros((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [6]:
tf.ones((4,5))

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [7]:
# Identity matrix
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [8]:
# from distribution
tf.random.normal((2,4,4), mean=0, stddev=1)

<tf.Tensor: shape=(2, 4, 4), dtype=float32, numpy=
array([[[-0.43060648,  1.1073517 ,  0.09527455,  0.85570836],
        [ 0.39146063,  0.64896744,  0.14328255,  1.1307526 ],
        [ 1.0997092 ,  0.22965698, -2.5004923 , -1.3351538 ],
        [-0.1516801 ,  0.6694153 , -0.10547091,  0.3335679 ]],

       [[ 1.3906739 , -0.1037313 , -1.0623549 , -0.17142649],
        [-0.6130908 ,  1.1789099 , -1.3516797 ,  1.7433486 ],
        [ 0.45900998,  0.14030571, -0.8124483 ,  1.8050551 ],
        [ 0.50466526,  0.43026027,  0.06378321,  2.4554286 ]]],
      dtype=float32)>

In [9]:
tf.random.uniform((2,3), minval=0, maxval=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.76082456, 0.30240262, 0.01234698],
       [0.23106647, 0.62917864, 0.25717533]], dtype=float32)>

In [10]:
tf.range(4)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [11]:
tf.range(start=1, limit=10, delta=4)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 5, 9], dtype=int32)>

In [12]:
# to change data type of vector
x = tf.range(start=1, limit=10, delta=4)
tf.cast(x, dtype=tf.float64)
# tf.int, tf.float

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 5., 9.])>

In [14]:
# Mathematical operations
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

In [18]:
# add or x + y - elementwise
z = tf.add(x,y)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [20]:
# subtract - elementwise
z = tf.subtract(x,y)
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [19]:
# multiply
z = tf.multiply(x,y)
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [21]:
# divide
z = tf.divide(x,y)
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [24]:
# dot product
z = tf.tensordot(x,y, axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [25]:
# matrix multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y) #or use x @ y
print(z)

tf.Tensor(
[[ 0.48773572  0.22985908 -1.9515271   0.34336185]
 [-0.72704244 -1.9164963  -0.04735786 -0.40394992]], shape=(2, 4), dtype=float32)


In [26]:
#Indexing
x = tf.constant([1,2,3,4,5,6])
x[::-1] # prints in reverse order

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([6, 5, 4, 3, 2, 1], dtype=int32)>

In [27]:
# every alternate element
x[::2]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 5], dtype=int32)>

In [30]:
# To get specific indexes
indices = tf.constant([1,2])
z = tf.gather(x,indices)
print(z)

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [31]:
# when you have multiple dimensions use , while indexing
x = tf.constant([[1,2],[3,4],[5,6]])
x[:2,:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [34]:
# reshaping
x = tf.range(8)
z = tf.reshape(x,(2,4))
print(z)

tf.Tensor(
[[0 1 2 3]
 [4 5 6 7]], shape=(2, 4), dtype=int32)


In [38]:
# Transpose
x = tf.range(8)
z = tf.reshape(x,(2,4))
tf.transpose(z, perm=[1,0]) # perm swap 0 and 1 axis

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]], dtype=int32)>